#include "include/network_bridge.h"
#include "include/property_service.h"
#include "include/logger.h"

#include <sys/types.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <sys/stat.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <poll.h>
#include <fcntl.h>
#include <unistd.h>
#include <cerrno>
#include <cstring>
#include <fstream>
#include <sstream>
#include <chrono>
#include <iomanip>

namespace gsi {

NetworkBridge& NetworkBridge::getInstance() {
    static NetworkBridge instance;
    return instance;
}

NetworkBridge::NetworkBridge() = default;

NetworkBridge::~NetworkBridge() {
    shutdown();
}

bool NetworkBridge::initialize(const std::string& sandboxDir,
                               const std::string& primaryDns,
                               const std::string& secondaryDns) {
    if (mIsRunning.load()) {
        LOGI("NetworkBridge already running");
        return true;
    }

    mSandboxDir = sandboxDir;
    if (!primaryDns.empty()) mPrimaryDns = primaryDns;
    if (!secondaryDns.empty()) mSecondaryDns = secondaryDns;

    LOGI("NetworkBridge: Initializing for sandbox '%s' (DNS1: %s, DNS2: %s)",
         mSandboxDir.c_str(), mPrimaryDns.c_str(), mSecondaryDns.c_str());

    provisionFiles();
    registerSystemProperties();

    // Setup UNIX domain socket for Virtual Netd daemon
    std::string socketDir = mSandboxDir + "/dev/socket";
    mkdir(socketDir.c_str(), 0755);

    mNetdSocketPath = socketDir + "/netd";
    unlink(mNetdSocketPath.c_str());

    mNetdServerFd = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (mNetdServerFd < 0) {
        LOGE("NetworkBridge: Failed to create netd server socket: %s", strerror(errno));
        return false;
    }

    struct sockaddr_un addr{};
    addr.sun_family = AF_UNIX;
    strncpy(addr.sun_path, mNetdSocketPath.c_str(), sizeof(addr.sun_path) - 1);

    if (bind(mNetdServerFd, reinterpret_cast<struct sockaddr*>(&addr), sizeof(addr)) < 0) {
        LOGE("NetworkBridge: Failed to bind netd socket to %s: %s", mNetdSocketPath.c_str(), strerror(errno));
        ::close(mNetdServerFd);
        mNetdServerFd = -1;
        return false;
    }

    if (listen(mNetdServerFd, 16) < 0) {
        LOGE("NetworkBridge: Failed to listen on netd socket: %s", strerror(errno));
        ::close(mNetdServerFd);
        mNetdServerFd = -1;
        return false;
    }

    chmod(mNetdSocketPath.c_str(), 0666);

    mIsRunning.store(true);
    mNetdThread = std::thread(&NetworkBridge::netdWorkerLoop, this);

    LOGI("NetworkBridge: Virtual Netd daemon listening at %s", mNetdSocketPath.c_str());
    return true;
}

void NetworkBridge::shutdown() {
    if (!mIsRunning.load()) return;

    LOGI("NetworkBridge: Shutting down Virtual Netd daemon");
    mIsRunning.store(false);

    if (mNetdServerFd >= 0) {
        ::close(mNetdServerFd);
        mNetdServerFd = -1;
    }

    if (!mNetdSocketPath.empty()) {
        unlink(mNetdSocketPath.c_str());
    }

    if (mNetdThread.joinable()) {
        mNetdThread.join();
    }

    LOGI("NetworkBridge: Shutdown complete");
}

void NetworkBridge::provisionFiles() {
    std::string etcDir = mSandboxDir + "/etc";
    mkdir(etcDir.c_str(), 0755);

    // 1. Provision /etc/resolv.conf
    std::string resolvPath = etcDir + "/resolv.conf";
    std::ofstream resolvFile(resolvPath, std::ios::trunc);
    if (resolvFile.is_open()) {
        resolvFile << "# Generated by GSI Virtual Network Bridge\n";
        resolvFile << "nameserver " << mPrimaryDns << "\n";
        resolvFile << "nameserver " << mSecondaryDns << "\n";
        resolvFile << "nameserver " << mIpv6Dns << "\n";
        resolvFile << "options timeout:2 attempts:3 rotate\n";
        resolvFile.close();
        chmod(resolvPath.c_str(), 0644);
        LOGI("NetworkBridge: Provisioned %s", resolvPath.c_str());
    } else {
        LOGE("NetworkBridge: Failed to create %s", resolvPath.c_str());
    }

    // 2. Provision /etc/hosts
    std::string hostsPath = etcDir + "/hosts";
    std::ofstream hostsFile(hostsPath, std::ios::trunc);
    if (hostsFile.is_open()) {
        hostsFile << "127.0.0.1       localhost\n";
        hostsFile << "::1             localhost ip6-localhost ip6-loopback\n";
        hostsFile << "127.0.0.1       " << mHostname << "\n";
        hostsFile.close();
        chmod(hostsPath.c_str(), 0644);
        LOGI("NetworkBridge: Provisioned %s", hostsPath.c_str());
    } else {
        LOGE("NetworkBridge: Failed to create %s", hostsPath.c_str());
    }
}

void NetworkBridge::registerSystemProperties() {
    auto& propService = PropertyService::getInstance();

    propService.setProperty("net.dns1", mPrimaryDns);
    propService.setProperty("net.dns2", mSecondaryDns);
    propService.setProperty("net.dns3", mIpv6Dns);
    propService.setProperty("net.change", "1");
    propService.setProperty("net.hostname", mHostname);
    propService.setProperty("net.gsi.status", "online");
    propService.setProperty("net.gsi.bridge", "passthrough");
    propService.setProperty("net.tcp.buffersize.default", "4096,87380,110208,4096,16384,110208");
    propService.setProperty("net.tcp.buffersize.wifi", "524288,1048576,2097152,262144,524288,1048576");

    LOGI("NetworkBridge: Registered DNS & TCP system properties in PropertyService");
}

void NetworkBridge::netdWorkerLoop() {
    LOGI("NetworkBridge: Worker thread started");

    while (mIsRunning.load()) {
        struct pollfd pfd{};
        pfd.fd = mNetdServerFd;
        pfd.events = POLLIN;

        int ret = poll(&pfd, 1, 500);
        if (ret < 0) {
            if (errno == EINTR) continue;
            break;
        }

        if (ret > 0 && (pfd.revents & POLLIN)) {
            struct sockaddr_un clientAddr{};
            socklen_t clientLen = sizeof(clientAddr);
            int clientFd = accept(mNetdServerFd, reinterpret_cast<struct sockaddr*>(&clientAddr), &clientLen);
            if (clientFd >= 0) {
                handleNetdClient(clientFd);
            }
        }
    }

    LOGI("NetworkBridge: Worker thread exited");
}

void NetworkBridge::handleNetdClient(int clientFd) {
    char buffer[1024];
    ssize_t bytesRead = read(clientFd, buffer, sizeof(buffer) - 1);
    if (bytesRead > 0) {
        buffer[bytesRead] = '\0';
        std::string cmd(buffer);

        {
            std::lock_guard<std::mutex> lock(mStatsMutex);
            mQueryCounter++;
        }

        LOGI("NetworkBridge: Netd query received (%zd bytes): '%s'", bytesRead, cmd.c_str());

        // Respond according to standard Android netd protocol
        // Format: "<response_code> <data>\n"
        std::string response;
        if (cmd.find("ping") != std::string::npos) {
            response = "200 0 PONG\n";
        } else if (cmd.find("getaddrinfo") != std::string::npos || cmd.find("resolver") != std::string::npos) {
            // Netd resolver acknowledge
            response = "200 0 Command succeeded\n";
        } else {
            response = "200 0 Command succeeded\n";
        }

        send(clientFd, response.c_str(), response.size(), MSG_NOSIGNAL);
    }

    ::close(clientFd);
}

std::string NetworkBridge::testConnectivity(const std::string& host, int port) {
    std::ostringstream ss;
    ss << "[NET BRIDGE TEST] Host: " << host << ":" << port << "\n";

    // 1. DNS Resolution Phase
    auto dnsStart = std::chrono::steady_clock::now();

    struct addrinfo hints{};
    hints.ai_family = AF_INET; // IPv4 for fast diagnostic
    hints.ai_socktype = SOCK_STREAM;

    struct addrinfo* res = nullptr;
    std::string portStr = std::to_string(port);

    int gaiRet = getaddrinfo(host.c_str(), portStr.c_str(), &hints, &res);
    auto dnsEnd = std::chrono::steady_clock::now();
    double dnsMs = std::chrono::duration<double, std::milli>(dnsEnd - dnsStart).count();

    if (gaiRet != 0 || !res) {
        ss << "[-] DNS Lookup FAILED: " << gai_strerror(gaiRet) << "\n";
        ss << "    Status: OFFLINE (DNS resolution error)";
        return ss.str();
    }

    char ipStr[INET_ADDRSTRLEN] = {0};
    auto* ipv4 = reinterpret_cast<struct sockaddr_in*>(res->ai_addr);
    inet_ntop(AF_INET, &(ipv4->sin_addr), ipStr, sizeof(ipStr));

    ss << "[+] DNS Resolved: " << ipStr << " in " << std::fixed << std::setprecision(1) << dnsMs << " ms\n";

    // 2. TCP 3-Way Handshake Connection Phase
    auto tcpStart = std::chrono::steady_clock::now();

    int sock = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
    if (sock < 0) {
        ss << "[-] Socket creation failed: " << strerror(errno) << "\n";
        freeaddrinfo(res);
        return ss.str();
    }

    // Set non-blocking for connect with timeout
    int flags = fcntl(sock, F_GETFL, 0);
    fcntl(sock, F_SETFL, flags | O_NONBLOCK);

    int connRet = connect(sock, res->ai_addr, res->ai_addrlen);
    if (connRet < 0 && errno == EINPROGRESS) {
        struct pollfd pfd{};
        pfd.fd = sock;
        pfd.events = POLLOUT;

        int pollRet = poll(&pfd, 1, 3000); // 3-second timeout
        if (pollRet > 0) {
            int sockErr = 0;
            socklen_t errLen = sizeof(sockErr);
            getsockopt(sock, SOL_SOCKET, SO_ERROR, &sockErr, &errLen);
            if (sockErr == 0) {
                connRet = 0; // Success
            } else {
                connRet = -1;
                errno = sockErr;
            }
        } else {
            connRet = -1;
            errno = ETIMEDOUT;
        }
    }

    auto tcpEnd = std::chrono::steady_clock::now();
    double tcpMs = std::chrono::duration<double, std::milli>(tcpEnd - tcpStart).count();

    ::close(sock);
    freeaddrinfo(res);

    if (connRet == 0) {
        ss << "[+] TCP Handshake: SUCCESS in " << std::fixed << std::setprecision(1) << tcpMs << " ms\n";
        ss << "[+] Socket Layer: Direct Unprivileged Passthrough ACTIVE\n";
        ss << "[+] Overall Status: ONLINE (RTT: " << std::fixed << std::setprecision(1) << (dnsMs + tcpMs) << " ms)";
    } else {
        ss << "[-] TCP Handshake FAILED (" << strerror(errno) << ") in " << std::fixed << std::setprecision(1) << tcpMs << " ms\n";
        ss << "    Status: DNS OK, TCP BLOCKED";
    }

    return ss.str();
}

std::string NetworkBridge::getNetworkStatsString() const {
    std::ostringstream ss;
    ss << "Virtual Netd: " << (mIsRunning.load() ? "ACTIVE" : "STOPPED")
       << " | DNS1: " << mPrimaryDns
       << " | DNS2: " << mSecondaryDns
       << " | Queries Handled: " << mQueryCounter;
    return ss.str();
}

NetworkStats NetworkBridge::getStats() const {
    std::lock_guard<std::mutex> lock(mStatsMutex);
    NetworkStats s;
    s.primaryDns = mPrimaryDns;
    s.secondaryDns = mSecondaryDns;
    s.ipv6Dns = mIpv6Dns;
    s.hostname = mHostname;
    s.isNetdRunning = mIsRunning.load();
    s.totalQueriesProcessed = mQueryCounter;
    return s;
}

} // namespace gsi
